---
# tasks file for db
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
    
- name: Change mongo config file      
  template:
    src: mongod.conf.j2 # <-- Path to local template
    dest: /etc/mongod.conf # <-- Path to remote host
    mode: 0644 # <-- Permisssions of file      
  notify: restart mongod